apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: seto
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: seto/app-secrets
        property: jwt-secret
    - secretKey: aes-secret-key
      remoteRef:
        key: seto/app-secrets
        property: aes-secret-key
