apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: seto
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: seto/db-credentials
        property: url
    - secretKey: username
      remoteRef:
        key: seto/db-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: seto/db-credentials
        property: password
    - secretKey: driver
      remoteRef:
        key: seto/db-credentials
        property: driver
