apiVersion: v1
kind: ServiceAccount
metadata:
  name: seto-kafka-sa
  namespace: seto
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::481961345072:role/eksctl-seto-cluster-addon-iamserviceaccount-s-Role1-ACxGTnlcPrp0"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: seto
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::481961345072:role/eksctl-seto-cluster-addon-iamserviceaccount-s-Role1-jlm7rC3AtDPS"
