apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: seto-kibana
  namespace: seto
spec:
  version: 8.12.0
  count: 1
  elasticsearchRef:
    name: seto-es
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 500m
