apiVersion: v1
kind: Service
metadata:
  name: hr
  namespace: seto
  labels:
    app: hr
spec:
  type: ClusterIP
  selector:
    app: hr
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
